/* Live competitor intelligence: normalized from public ad-library audits pulled 2026-09-06. */
var COMPETITOR_BRANDS={
  all:{name:'Category view',ads:677,dynamic:'60.4%',fixed:'Three distinct',funnel:'Subscription-led',focus:'Test mechanisms, not copies',
    note:'Across the sample, each brand uses a large dynamic layer and a smaller fixed-creative layer. The useful decision is which mechanism TWC should validate—not which competitor has the most ads.',
    stages:[['Discovery','Dynamic reach + fixed concepts','Catalog or flexible delivery creates breadth while authored ads communicate one idea.'],['Education','Creator, routine, proof or offer','Fixed executions explain why the product belongs in a customer’s life.'],['Pre-sell','Quiz, advertorial or collection','The destination reduces uncertainty before the product decision.'],['Conversion','PDP + subscription mechanics','Offer, bundle, guarantee and replenishment economics shape conversion.'],['Retention','Renewal + cross-sell','Subscription creates the base; retention quality determines allowable CAC.']],
    patterns:[['Always-on plus test layer','All three show high dynamic/catalog activity alongside fixed ads. Keep discovery and learning jobs separate.'],['Destination is part of creative','Quiz, advertorial, PDP and collection routes change what the ad must explain. Judge the entire path.'],['Scale follows recurring economics','Subscription is visible throughout the set. Scale from backend contribution and retention—not platform ROAS alone.']]},
  Ritual:{name:'Ritual',ads:147,dynamic:'55.1%',fixed:'26.5% static',funnel:'PDP / set → subscribe',focus:'Bundles + trust',
    note:'A broad portfolio is organized through dynamic delivery, life-stage starter sets, product pages and trust signals. UGC is a small part of the observed mix.',
    stages:[['Discovery','DCO / DPA + sale creative','55.1% of sampled ads are dynamic or catalog formats.'],['Education','Benefit, clinical proof, UGC','Fixed ads frame a product-specific reason to care.'],['Consideration','Product, collection or starter set','Life-stage sets and collections reduce portfolio complexity.'],['Conversion','Subscription-first checkout','Welcome and subscriber offers are generally auto-applied.'],['Retention','Renewal + portfolio cross-sell','Likely commercial role; retention performance is not visible in Ad Library.']],
    patterns:[['Starter sets simplify choice','Bundle and life-stage creative accounted for a meaningful fixed layer.'],['Trust can be an angle','Traceability, studied ingredients and guarantee language recur. Verify every TWC proof point.'],['Portfolio gaps are testable','Low observed UGC and uneven SKU coverage can inspire a test, but not a conclusion about performance.']]},
  Seed:{name:'Seed',ads:422,dynamic:'58.5%',fixed:'28.4% video',funnel:'87.2% → quiz',focus:'Creator + quiz',
    note:'The flagship DS-01 dominates the sample. A large DCO base is reinforced by creator whitelisting, affiliate codes and a highly concentrated quiz route.',
    stages:[['Discovery','DCO + creator whitelisting','Dynamic reach is paired with a deep creator layer.'],['Education','UGC, brand proof, offers','Creators add context while branded work carries institutional proof.'],['Pre-sell','“Is DS-01 right for you?” quiz','87.2% of sampled ads route to the multi-question quiz.'],['Conversion','$49.99/month subscription default','The quiz resolves into a flagship subscription decision.'],['Retention','Replenishment + product expansion','Commercial role is plausible; renewal and win-back results are not public.']],
    patterns:[['Creator operations are infrastructure','30.6% of the sample is creator-whitelisted UGC, with many affiliate codes.'],['One destination can carry scale','The quiz centralizes education and offer handling, but must be tested against a direct PDP.'],['Concentration creates both clarity and risk','89.8% of sampled ads promote DS-01; TWC should avoid unmeasured single-product dependence.']]},
  Supergut:{name:'Supergut',ads:108,dynamic:'75.0%',fixed:'20.4% video',funnel:'59.3% → subscription link',focus:'Habit + direct subscribe',
    note:'The most dynamic-heavy set combines catalog coverage with habit-led video, fiber education and direct Subscribe & Save product links.',
    stages:[['Discovery','DCO / DPA / carousel','75% of sampled ads are dynamic or catalog-oriented.'],['Education','Habit, trend and product choice','Routine-led video and fiber education translate the category.'],['Pre-sell','PDP, collection or advertorial','Different destinations support product, portfolio and trend narratives.'],['Conversion','Subscribe & Save deep link','59.3% of sampled links contain a Shopify selling-plan parameter.'],['Retention','Daily habit + replenishment','The product is framed as a routine; actual retention is not observable.']],
    patterns:[['Habit is a creative mechanism','Morning and ease-of-use narratives make repeat use concrete.'],['Direct subscription can remove friction','Preselected selling plans can shorten the path, but TWC must test consent clarity and conversion quality.'],['Advertorials need one job','A pre-sell page should carry one primary next step and preserve message match.']]}
};

var COMPETITOR_ADS=[
 {brand:'Ritual',id:'1469035961720134',date:'2026-09-05',days:1,format:'Video',concept:'Bundle / starter set',stage:'Consideration',product:'Daily Health 50+ Starter Set',headline:'Daily Health 50+ Starter Set',destination:'Starter-set page',ad:'https://www.facebook.com/ads/library/?id=1469035961720134',preview:'https://app.foreplay.co/discovery?ad=y9AMDvHp3Rp7jA2FAIke'},
 {brand:'Ritual',id:'1622717859239062',date:'2026-09-05',days:1,format:'DPA',concept:'Dynamic catalog',stage:'Discovery',product:'Portfolio',headline:'Dynamic ad — fixed copy unavailable',destination:'Homepage',ad:'https://www.facebook.com/ads/library/?id=1622717859239062',preview:'https://app.foreplay.co/discovery?ad=vgeMMbfz27HKrGQSgSZn'},
 {brand:'Ritual',id:'2135056224023573',date:'2026-09-05',days:1,format:'Video',concept:'Guarantee / trust',stage:'Conversion',product:'Daily Health collection',headline:'30 day, money-back guarantee',destination:'Collection page',ad:'https://www.facebook.com/ads/library/?id=2135056224023573',preview:'https://app.foreplay.co/discovery?ad=eqjFVej2MFbo4zPJR1iu'},
 {brand:'Ritual',id:'1386247022988887',date:'2026-09-05',days:1,format:'Image',concept:'Clinical proof',stage:'Education',product:'Magnesium+',headline:'Magnesium Bisglycinate Chelate',destination:'Product page',ad:'https://www.facebook.com/ads/library/?id=1386247022988887',preview:'https://app.foreplay.co/discovery?ad=0PlciiHi0i1B5JPMzAIK'},
 {brand:'Ritual',id:'2636445993463093',date:'2026-09-04',days:2,format:'Video',concept:'Creator / UGC',stage:'Education',product:'Sleep BioSeries',headline:'The daily essential lineup',destination:'Product page',ad:'https://www.facebook.com/ads/library/?id=2636445993463093',preview:'https://app.foreplay.co/discovery?ad=mYgV5ikV3eE0vcJ8gOCn'},
 {brand:'Seed',id:'38072153219096760',date:'2026-09-05',days:1,format:'Video',concept:'Creator whitelisting',stage:'Discovery',product:'DS-01',headline:'Creator offer with affiliate code',destination:'DS-01 quiz',ad:'https://www.facebook.com/ads/library/?id=38072153219096760',preview:'https://app.foreplay.co/discovery?ad=oebLWuiX5jYYKNPtOjft'},
 {brand:'Seed',id:'1974971303220290',date:'2026-09-05',days:1,format:'Video',concept:'Benefit direct response',stage:'Education',product:'DS-01',headline:'DS-01® gets you going like clockwork',destination:'DS-01 quiz',ad:'https://www.facebook.com/ads/library/?id=1974971303220290',preview:'https://app.foreplay.co/discovery?ad=Z59ghigeaMGeWoE2Ah7v'},
 {brand:'Seed',id:'4585002595044655',date:'2026-09-04',days:2,format:'DCO',concept:'Dynamic prospecting',stage:'Discovery',product:'DS-01',headline:'Dynamic ad — fixed copy unavailable',destination:'DS-01 quiz',ad:'https://www.facebook.com/ads/library/?id=4585002595044655',preview:'https://app.foreplay.co/discovery?ad=yYTo3Db3OtqbNYWOkfBV'},
 {brand:'Seed',id:'1012452931826006',date:'2026-09-04',days:2,format:'Image',concept:'Institutional proof',stage:'Education',product:'DS-01',headline:'Product facts and risk-free framing',destination:'DS-01 quiz',ad:'https://www.facebook.com/ads/library/?id=1012452931826006',preview:'https://app.foreplay.co/discovery?ad=dozzySIYnN8tXIaxT0GE'},
 {brand:'Seed',id:'1040681755518097',date:'2026-08-23',days:14,format:'Image',concept:'Risk reversal / welcome kit',stage:'Conversion',product:'DS-01',headline:'Offer plus free Welcome Kit',destination:'DS-01 quiz',ad:'https://www.facebook.com/ads/library/?id=1040681755518097',preview:'https://app.foreplay.co/discovery?ad=ASKvkZIQfmPYvjJwoInt'},
 {brand:'Supergut',id:'2411594216037762',date:'2026-09-05',days:1,format:'Video',concept:'Ease-of-use UGC',stage:'Education',product:'Foundational Daily Fiber',headline:'Fiber Made Easy',destination:'Subscription PDP',ad:'https://www.facebook.com/ads/library/?id=2411594216037762',preview:'https://app.foreplay.co/discovery?ad=2jVXUayINauKnBkGUkFE'},
 {brand:'Supergut',id:'1075498648405597',date:'2026-09-04',days:2,format:'DCO',concept:'Dynamic prospecting',stage:'Discovery',product:'Portfolio',headline:'Dynamic ad — fixed copy unavailable',destination:'Collection page',ad:'https://www.facebook.com/ads/library/?id=1075498648405597',preview:'https://app.foreplay.co/discovery?ad=tY1YmFltUSb8FQg1gVOH'},
 {brand:'Supergut',id:'1227041190503741',date:'2026-09-03',days:3,format:'Image',concept:'Trend / fibermaxxing',stage:'Pre-sell',product:'Foundational Daily Fiber',headline:'Fibermaxxing Starts Here',destination:'Advertorial + subscription',ad:'https://www.facebook.com/ads/library/?id=1227041190503741',preview:'https://app.foreplay.co/discovery?ad=2vUaZ2CWpsmWfBs2TJkZ'},
 {brand:'Supergut',id:'1579854257269686',date:'2026-09-02',days:4,format:'Video',concept:'Morning routine',stage:'Education',product:'Foundational Daily Fiber',headline:'Before Your Coffee, Do This',destination:'Subscription PDP',ad:'https://www.facebook.com/ads/library/?id=1579854257269686',preview:'https://app.foreplay.co/discovery?ad=LajAWW5F68HkHP5964JZ'},
 {brand:'Supergut',id:'1829784128180784',date:'2026-08-31',days:6,format:'Video',concept:'Product education',stage:'Consideration',product:'Portfolio',headline:'Two Fibers. Different Benefits.',destination:'Collection page',ad:'https://www.facebook.com/ads/library/?id=1829784128180784',preview:'https://app.foreplay.co/discovery?ad=1NxgCobntwVzeN97wtx3'}
];

var COMPETITOR_TESTS=[
 {id:'FNL-01',title:'Direct PDP vs educational pre-sell',source:'Seed centralizes 87.2% of sampled ads on a quiz; Supergut also uses an advertorial.',test:'Keep concept, audience, offer and optimization event fixed. Change only destination: reviewed PDP vs reviewed pre-sell.',gate:'Backend CPA, landing rate and checkout rate clear target after the minimum read.',risk:'No sensitive-health profiling; review every page claim and data field.',go:'experiments'},
 {id:'CRT-01',title:'Brand vs creator expression',source:'Seed’s sample contains a substantial creator-whitelisting layer alongside DCO.',test:'Express one approved mechanism as brand-led and creator-led variants inside controlled ABO cells.',gate:'A winner must clear backend CPA and qualified funnel rates—not CTR alone.',risk:'Verify testimonial, disclosure, usage rights and claim references.',go:'pipeline'},
 {id:'OFF-01',title:'Single product vs starter bundle',source:'Ritual uses starter sets and life-stage collections to simplify a wide portfolio.',test:'Compare the same problem frame with a single reviewed product and a clear contents-led bundle.',gate:'Contribution after discount, AOV, new-customer CPA and refund rate remain acceptable.',risk:'Use exact contents, price, term and availability. No implied clinical outcome.',go:'offers'},
 {id:'MSG-01',title:'Routine / habit vs product facts',source:'Supergut repeatedly turns product use into a morning, nighttime or ease-of-use routine.',test:'Keep product and offer fixed; compare a claim-safe routine story with a factual product explanation.',gate:'Both the ad and destination preserve message match; winner clears CPA after minimum spend.',risk:'Routine framing cannot smuggle in blood-sugar, symptom or treatment claims.',go:'briefs'},
 {id:'SCL-01',title:'Eligible catalog layer vs fixed winners',source:'Dynamic/catalog formats represent 55–75% of each audit sample.',test:'Only for catalog-safe SKUs: isolate an always-on dynamic layer from the fixed creative test layer.',gate:'Incremental budget clears marginal CPA/MER, catalog feed health and creative concentration limits.',risk:'Exclude gated or claim-sensitive products until written eligibility and feed review clear.',go:'scaleops'},
 {id:'RET-01',title:'Subscription entry quality',source:'Subscription mechanics dominate the observed Seed and Supergut conversion paths.',test:'Compare one-time or neutral entry with clearly disclosed subscription value where commercially allowed.',gate:'Use contribution, cancellation, refund and retained-customer value—not day-one ROAS alone.',risk:'Terms, renewal, price and consent must be explicit and match checkout.',go:'ltv'}
];

var competitorState={brand:'all',query:'',format:'',stage:''};
function compEsc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function compOptions(values,label){return '<option value="">'+compEsc(label)+'</option>'+values.map(function(v){return '<option>'+compEsc(v)+'</option>'}).join('')}
function compMetric(label,value,detail){return '<div><span>'+compEsc(label)+'</span><b>'+compEsc(value)+'</b><small>'+compEsc(detail)+'</small></div>'}
function compSummary(brand){return '<div class="comp-summary"><div class="lead"><span>Current read</span><b>'+compEsc(brand.focus)+'</b><small>'+compEsc(brand.note)+'</small></div>'+compMetric('Ads sampled',brand.ads,'Active on pull date')+compMetric('Dynamic / catalog',brand.dynamic,'Share of sampled ads')+compMetric('Fixed layer',brand.fixed,'Most useful authored signal')+compMetric('Observed path',brand.funnel,'Destination pattern, not performance')+'</div>'}
function compFunnel(brand){return '<div class="comp-funnel">'+brand.stages.map(function(s,i){return '<article class="comp-stage"><span>0'+(i+1)+' · '+compEsc(s[0])+'</span><b>'+compEsc(s[1])+'</b><p>'+compEsc(s[2])+'</p></article>'}).join('')+'</div>'}
function compPatterns(brand){return '<div class="comp-patterns">'+brand.patterns.map(function(p){return '<div class="comp-pattern"><b>'+compEsc(p[0])+'</b><span>'+compEsc(p[1])+'</span></div>'}).join('')+'</div>'}
function compFilteredAds(){var q=competitorState.query.toLowerCase();return COMPETITOR_ADS.filter(function(ad){return (competitorState.brand==='all'||ad.brand===competitorState.brand)&&(!competitorState.format||ad.format===competitorState.format)&&(!competitorState.stage||ad.stage===competitorState.stage)&&(!q||[ad.brand,ad.concept,ad.product,ad.headline,ad.destination].join(' ').toLowerCase().includes(q))})}
function compAdsTable(){var rows=compFilteredAds();if(!rows.length)return '<div class="comp-empty">No examples match these filters.</div>';return '<div class="tw"><table class="comp-ad-table"><thead><tr><th>Brand / concept</th><th>Example</th><th>Funnel role</th><th>Snapshot</th><th>Open</th></tr></thead><tbody>'+rows.map(function(ad){return '<tr><td><b>'+compEsc(ad.brand)+'</b><span class="comp-ad-sub">'+compEsc(ad.concept)+'</span></td><td><span class="comp-ad-main">'+compEsc(ad.headline)+'</span><span class="comp-ad-sub">'+compEsc(ad.product)+'</span></td><td><span class="comp-tag">'+compEsc(ad.stage)+'</span><span class="comp-ad-sub">'+compEsc(ad.destination)+'</span></td><td><span class="comp-tag '+(/DCO|DPA/.test(ad.format)?'dynamic':'')+'">'+compEsc(ad.format)+'</span><span class="comp-ad-sub">Started '+compEsc(ad.date)+' · '+compEsc(ad.days)+'d on pull date</span></td><td><a href="'+compEsc(ad.ad)+'" target="_blank" rel="noopener noreferrer">Meta <i class="bi bi-box-arrow-up-right"></i></a><br><a href="'+compEsc(ad.preview)+'" target="_blank" rel="noopener noreferrer">Foreplay <i class="bi bi-box-arrow-up-right"></i></a></td></tr>'}).join('')+'</tbody></table></div>'}
function compTests(){return '<div class="comp-test-grid">'+COMPETITOR_TESTS.map(function(t){return '<article class="comp-test"><span>'+compEsc(t.id)+'</span><h4>'+compEsc(t.title)+'</h4><p>'+compEsc(t.source)+'</p><dl><dt>Controlled test</dt><dd>'+compEsc(t.test)+'</dd><dt>Scale gate</dt><dd>'+compEsc(t.gate)+'</dd><dt>Boundary</dt><dd>'+compEsc(t.risk)+'</dd></dl><button class="btn sm" type="button" data-go="'+compEsc(t.go)+'">Open tool</button></article>'}).join('')+'</div>'}
function compDraw(){var root=$('competitor-app');if(!root)return;var brand=COMPETITOR_BRANDS[competitorState.brand];root.innerHTML='<div class="comp-tabs" role="tablist" aria-label="Competitor view">'+Object.keys(COMPETITOR_BRANDS).map(function(key){var item=COMPETITOR_BRANDS[key];return '<button class="comp-tab '+(key===competitorState.brand?'on':'')+'" type="button" role="tab" aria-selected="'+(key===competitorState.brand)+'" data-comp-brand="'+compEsc(key)+'"><span>'+compEsc(item.name)+'</span><b>'+item.ads+'</b></button>'}).join('')+'</div>'+compSummary(brand)+
  '<div class="comp-grid"><div class="panel comp-panel"><div class="comp-panel-head"><div><h3>Observed funnel</h3><p>Destination and offer mechanics visible in the audit.</p></div><span class="comp-tag">Snapshot, not account structure</span></div>'+compFunnel(brand)+'</div><div class="panel comp-panel"><div class="comp-panel-head"><div><h3>What transfers</h3><p>Mechanisms worth validating for TWC.</p></div></div>'+compPatterns(brand)+'</div></div>'+
  '<div class="panel"><div class="comp-panel-head"><div><h3>Live ad examples</h3><p id="comp-result-count">'+compFilteredAds().length+' normalized examples · links can change after the pull date</p></div><button class="btn sm" type="button" data-go="compete">Open manual tracker</button></div><div class="comp-controls"><input id="comp-search" type="search" placeholder="Search concept, product or destination" value="'+compEsc(competitorState.query)+'">'+'<select id="comp-brand-filter" aria-label="Filter brand">'+compOptions(['Ritual','Seed','Supergut'],'All brands').replace('option>'+compEsc(competitorState.brand)+'</option>','option selected>'+compEsc(competitorState.brand)+'</option>')+'</select><select id="comp-format" aria-label="Filter format">'+compOptions(['DCO','DPA','Image','Video'],'All formats')+'</select><select id="comp-stage" aria-label="Filter funnel stage">'+compOptions(['Discovery','Education','Pre-sell','Consideration','Conversion'],'All funnel stages')+'</select></div><div id="comp-ad-results">'+compAdsTable()+'</div></div>'+
  '<div class="panel"><div class="comp-panel-head"><div><h3>TWC test queue</h3><p>Six competitor-informed hypotheses. Each still has to earn scale with TWC evidence.</p></div><button class="btn sm" type="button" data-go="pipeline">Open testing system</button></div>'+compTests()+'<div class="comp-boundary"><div><b>Public facts</b><p>Ad, format, copy, start date, destination and visible offer on the pull date.</p></div><div><b>Reasonable inference</b><p>Likely funnel job or operating mechanism, clearly labeled and tested internally.</p></div><div><b>Not observable</b><p>Spend, ad set structure, targeting, CPA, ROAS, conversion rate and incrementality.</p></div><div><b>Scale decision</b><p>Made only from TWC backend economics, delivery stability, creative depth and compliance clearance.</p></div></div></div>';
  if(competitorState.format)$('comp-format').value=competitorState.format;if(competitorState.stage)$('comp-stage').value=competitorState.stage;
}
function renderCompetitors(){var root=$('competitor-app');if(!root)return;compDraw();if(root.dataset.bound)return;root.dataset.bound='true';root.addEventListener('click',function(event){var button=event.target.closest('[data-comp-brand]');if(!button)return;competitorState.brand=button.dataset.compBrand;compDraw()});root.addEventListener('input',function(event){if(event.target.id==='comp-search'){competitorState.query=event.target.value;$('comp-ad-results').innerHTML=compAdsTable();$('comp-result-count').textContent=compFilteredAds().length+' normalized examples · links can change after the pull date'}});root.addEventListener('change',function(event){if(event.target.id==='comp-brand-filter')competitorState.brand=event.target.value||'all';if(event.target.id==='comp-format')competitorState.format=event.target.value;if(event.target.id==='comp-stage')competitorState.stage=event.target.value;compDraw()})}

/* Initialize independently so a cached application boot file cannot leave this view empty. */
if(typeof document!=='undefined'){
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderCompetitors);
  else renderCompetitors();
}
