/* TWC restart operating plan. Manual records; no ad-platform actions or policy guarantees. */
var RS_SOURCE='TWC Account Restart Plan · supplied PDF · sections 3, 6–14';
PL_FIELDS[0][1].push(['restartCell','Restart cell (leave empty for other work)','select',['','skin-1','skin-2','skin-3','skin-4','skin-mixed','kit-1','kit-2','kit-3','kit-4']],['creativeStyle','Creative style / container']);
PL_FIELDS.splice(1,0,['Copy draft: reviewed for this product',[
 ['copyStructure','Structure','select',['Not selected','Kit · indirect','Skincare · direct']],['copyHook','Opening hook','textarea'],['copyTurn','Kit: calm reframe / skincare: specific detail','textarea'],['copyProduct','Product description (actual SKU)','textarea'],['copyProof','One verified proof; link its claim in approval fields','textarea'],['copyOffer','Accurate price / offer / subscription terms','textarea'],['copyCta','Call to action'],['copyNotes','Claim restrictions and destination message match','textarea']]]);
var RS_CHECKS=[
 ['reason','Restriction reason retrieved and remediation documented',true],
 ['testimonials','Outcome testimonials removed from paid destinations',true],
 ['claims','Quantified announcement-bar claims removed',true],
 ['events','Pixel and CAPI verified in Test Events',true],
 ['dedup','Deduplication checked for every transmitted event',true],
 ['orders','Value and currency reconciled against five real orders',true],
 ['domain','Domain ownership and current event configuration verified',true],
 ['landing','LP-02 live; eligibility and conversion checks cleared',true],
 ['utm','UTM taxonomy consistent with campaign naming',false],
 ['audiences','Purchaser, staff and intended warm exclusions prepared',false],
 ['targets','Per-product targets agreed in writing',false],
 ['owner','Compliance owner, backup and turnaround agreed',false]
];
function rsDefaults(){return {version:2,assetsPerCell:6,kitConcepts:['Preparedness','Access','Variant C','Variant D'],start:'',reason:'Unknown',reasonEvidence:'',remediated:false,alternativeReviewed:false,owner:'',backup:'',decision:'',accepted:false,skinName:'Skincare hero',kitName:'Non-Rx preparedness kit',skinCpa:35,kitCpa:90,ramp:[600,900,1200,1500],week:1,mixed:false,skinConcepts:['Concept A','Concept B','Concept C','Concept D'],checks:{},checkEvidence:'',catalogTier:false,catalogSet:false,catalogReview:false,catalogEvidence:'',reads:[],days:[]}}
function rsState(){var p=plState();if(!p.restart)p.restart=rsDefaults();return p.restart}
function rsProduct(lane){return lane==='skin'?rsState().skinName:rsState().kitName}
function rsCells(s){s=s||rsState();return ['skin','kit'].flatMap(function(lane){var names=lane==='skin'?s.skinConcepts:(s.kitConcepts||rsDefaults().kitConcepts);return names.map(function(name,i){return {id:lane+'-'+(i+1),lane:lane,concept:name,kind:'Concept',index:i+1}})})}
function rsCell(id){return rsCells().find(function(c){return c.id===id})}
function rsCampaign(c){return 'TWC_US_'+(c.lane==='skin'?'SKINCARE':'FIRSTAID-KIT')+'_ACQ_'+(c.kind==='Mixed'?'PERFORMANCE':'CT-CONCEPT')+'_ABO'}
function rsEconomics(s,lane,week){var budget=s.ramp[(week||s.week)-1],count=4,cpa=lane==='skin'?s.skinCpa:s.kitCpa;return {daily:budget,perCell:budget/count,weeklyOrders:budget/count*7/cpa,maxCells:Math.floor(budget*7/(50*cpa)),count:count}}
function rsSpend(s,days){var sum=0;for(var i=0;i<days;i++)sum+=s.ramp[Math.min(3,Math.floor(i/7))]*2;return sum}
function rsLaunchIssues(s){s=s||rsState();var issues=[];if(!s.accepted||!String(s.decision||'').trim())issues.push('Record the approved budget and structure decision');if(!plValidDate(s.start))issues.push('Set the restart start date');if(s.reason==='Unknown'||!wsSafeLink(s.reasonEvidence)||!s.remediated)issues.push('Resolve and evidence the original restriction');if(s.reason==='Supplement / skincare claim'&&(!s.alternativeReviewed||s.skinName==='Skincare hero'))issues.push('Select a non-claim replacement for skincare and record its eligibility review');if(!String(s.owner||'').trim()||!String(s.backup||'').trim())issues.push('Name the compliance owner and backup');if(!String(s.checkEvidence||'').trim())issues.push('Add week-zero verification evidence');RS_CHECKS.forEach(function(c){if(c[2]&&!s.checks[c[0]])issues.push(c[1])});return issues}
function rsCatalogIssues(s){s=s||rsState();return rsLaunchIssues(s).concat(s.catalogTier&&s.catalogSet&&s.catalogReview&&wsSafeLink(s.catalogEvidence)?[]:['Catalog requires verified tier mapping, two-SKU allowlist, reviewed feed/destinations and evidence'])}
function rsInput(key,label,value,type,extra){return '<label>'+label+'<input name="'+key+'" type="'+(type||'text')+'" value="'+plE(value)+'" '+(extra||'')+'></label>'}
function rsCheck(key,label,checked){return '<label class="pl-check"><input type="checkbox" name="'+key+'" '+(checked?'checked':'')+'>'+label+'</label>'}
function rsOptions(list,value){return list.map(function(v){return '<option '+(v===value?'selected':'')+'>'+plE(v)+'</option>'}).join('')}
function rsShell(){var s=rsState(),issues=rsLaunchIssues(s);return '<div class="rs-status"><div><span class="rs-kicker">90-day account restart</span><h3>'+(issues.length?'Week zero: '+issues.length+' launch blockers':'Week-zero checks recorded')+'</h3><p>Protect the account. Learn the concept. Confirm the asset. Earn expansion.</p></div><div class="rs-state '+(issues.length?'rs-hold':'rs-clear')+'">'+(issues.length?'SPEND ON HOLD':'REVIEW BEFORE LAUNCH')+'</div></div><div class="rs-phases"><div><b>00 · Clear</b><span>No media spend</span></div><div><b>01 · Learn</b><span>Concept cells · ABO</span></div><div><b>02 · Graduate</b><span>Scale 70 / test 15 / warm 15</span></div><div><b>03 · Prove</b><span>Same two products · day 90 gate</span></div></div>'}
function rsPlan(){var s=rsState(),issues=rsLaunchIssues(s);return rsShell()+
 '<div class="pl-notice">'+plE(RS_SOURCE)+'. These are client-plan assumptions and manual attestations, not current platform-policy certification. No checkbox guarantees approval. Source contradictions are recorded below.</div>'+
 '<form id="rs-plan" class="panel"><h3>1. Resolve the restart</h3><div class="pl-grid">'+
 rsInput('start','Restart start date',s.start,'date','required')+'<label>Original restriction<select name="reason">'+rsOptions(['Unknown','Rx / gated product','Destination issue','Supplement / skincare claim','Business verification','Other documented cause'],s.reason)+'</select></label>'+
 rsInput('reasonEvidence','Account Quality / remediation evidence URL',s.reasonEvidence,'url')+rsInput('owner','Compliance owner',s.owner)+rsInput('backup','Backup owner',s.backup)+rsCheck('remediated','Stated cause remediated and reviewed',s.remediated)+
 rsCheck('alternativeReviewed','Non-claim replacement eligibility reviewed (required for a skincare-claim restriction)',s.alternativeReviewed)+rsInput('skinName','Product two: reviewed skincare SKU or non-claim replacement',s.skinName)+rsInput('kitName','Product one: confirmed non-prescription kit SKU',s.kitName)+rsInput('skinCpa','Product two target CPA, USD',s.skinCpa,'number','min="0.01" step="any" required')+rsInput('kitCpa','Kit target CPA, USD',s.kitCpa,'number','min="0.01" step="any" required')+'</div>'+
 '<details class="rs-details"><summary>Budget decision and source conflicts</summary><p>The cover and section 9 retain a ~$27k/month, $260/$640 daily mixed-set build. Sections 8 and 11 instead describe $1,500/day per product and concept cells. The current instruction supersedes the PDF structure: four ABO ad sets per product campaign, one variant per set, four to twelve assets per cell. Confirm the actual media budget before spending.</p>'+plTable(['Source conflict','Operational treatment'],[
 ['Older cell counts and mixed pool','Current structure: four ABO ad sets per product; one variant in each. Prior mixed-pool records remain historical.'],['36 vs 42 ads','Current structure: 16–48 assets per product campaign; 32–96 across the two products.'],['All ramp steps called 50%','600 → 900 → 1,200 → 1,500 is +50%, +33.3%, +25%. Calculations use the entered amounts.'],['14 days without edits vs weekly ramp','Plan budget changes separately. Log material changes; restart the comparison window when required. Safety and loss stops take precedence.'],['8 vs 9 blocking week-zero items','Section 7 lists eight blocking checks. Budget approval and named ownership are additional console gates.'],['AC-01 removed vs included in copy examples','No claim approvals are inherited. Review every claim against the actual selected SKU.'],['50 conversions/week asserted as guaranteed learning','Use as a planning benchmark only, never proof of stable delivery or statistical confidence.']])+ '<div class="pl-grid">'+s.ramp.map(function(v,i){return rsInput('ramp'+i,'Week '+(i+1)+(i===3?'+':'')+' daily budget per product, USD',v,'number','min="0" step="any" required')}).join('')+'<label>Planning week<select name="week">'+[1,2,3,4].map(function(v){return '<option value="'+v+'" '+(s.week===v?'selected':'')+'>Week '+v+(v===4?'+':'')+'</option>'}).join('')+'</select></label>'+'<p>Four ABO cells per product. Product daily budget is split evenly across the four ad sets.</p>'+'<label class="pl-wide">Approved budget / structure decision and evidence reference<textarea name="decision">'+plE(s.decision)+'</textarea></label>'+rsCheck('accepted','Client budget and structure decision recorded',s.accepted)+'</div></details>'+
 '<h3>2. Complete week zero</h3><div class="rs-checklist">'+RS_CHECKS.map(function(c){return rsCheck('check_'+c[0],c[1]+(c[2]?' · blocks launch':' · operational follow-up'),s.checks[c[0]])}).join('')+'</div><label class="rs-textarea">Verification log / evidence references<textarea name="checkEvidence">'+plE(s.checkEvidence)+'</textarea></label><p>LP eligibility: reviewed claims, testimonials, navigation and cross-sells. LP conversion: message match, one primary action, accurate rating/count, price and delivery together, refund terms, genuine offer deadline where applicable. LP-02 blocks launch; LP-01 follows in week two, offer page in week three, LP-03 quiz in month two.</p>'+
 '<details class="rs-details"><summary>Optional catalog lane: separately gated and budgeted</summary><div class="pl-grid">'+rsCheck('catalogTier','product_type mapped to reviewed compliance tiers',s.catalogTier)+rsCheck('catalogSet','Allowlist limited to the two reviewed SKUs',s.catalogSet)+rsCheck('catalogReview','Feed and every destination verified',s.catalogReview)+rsInput('catalogEvidence','Catalog verification URL',s.catalogEvidence,'url')+'</div><p>No catalog allocation is assumed in the hand-built budget. Assign its funding explicitly before launch; never add it on top silently.</p></details><p id="rs-plan-errors" role="alert"></p><button class="btn p">Save restart decisions</button></form>'+
 '<div class="rs-lanes">'+['skin','kit'].map(function(lane){var e=rsEconomics(s,lane);return '<article class="panel"><span class="rs-kicker">'+(lane==='skin'?'Fast learning lane':'Margin proof lane')+'</span><h3>'+plE(rsProduct(lane))+'</h3>'+plStats([['Daily product budget',wsMoney(e.daily)],['Daily per cell',wsMoney(e.perCell)],['Expected orders / cell / week',e.weeklyOrders.toFixed(1)],['Cells at planning benchmark',e.maxCells]])+'<p class="'+(e.weeklyOrders<50?'pl-bad':'pl-muted')+'">'+(e.weeklyOrders<50?'Below the 50/week planning benchmark with four cells. Review evidence duration and funding before launch; this warning does not change the four-cell structure.':'Budget arithmetic clears the planning benchmark; actual CPA and delivery may differ.')+'</p></article>'}).join('')+'</div>'+
 '<h3>Ramp arithmetic</h3>'+plTable(['Week','Daily / product','Change','Two-product weekly spend'],s.ramp.map(function(v,i){return [i+1,wsMoney(v),i&&s.ramp[i-1]>0?((v/s.ramp[i-1]-1)*100).toFixed(1)+'%':'Start',wsMoney(v*14)]}))+plStats([['30-day ramped media',wsMoney(rsSpend(s,30))],['30-day full-ramp media',wsMoney(s.ramp[3]*60)],['Catalog readiness',rsCatalogIssues(s).length?'Blocked':'Recorded checks clear']])+
 '<p class="pl-notice">Advance a ramp step only after reviewing account health, mature backend CPA, marginal contribution and the billing limit. A high first-month CPA is a planning risk, not permission to ignore a loss limit. If efficiency deteriorates, hold and document a redirect to creative, landing pages or retention economics.</p>'+
 '<details class="rs-details"><summary>Current blockers ('+issues.length+')</summary><ul>'+issues.map(function(v){return '<li>'+plE(v)+'</li>'}).join('')+'</ul></details>'}
var RS_SKIN_FORMATS=[['UGC','9:16','Video',31],['Offer','4:5','Static',3],['White board','1:1','Video',5],['Native story','9:16','Video',21],['Doodle','4:5','Static',8],['Tier list','1:1','Static',20]];
var RS_KIT_FORMATS=[['iPhone notes','9:16','Static',11],['Native UGC','9:16','Video',31],['White board','1:1','Video',5],['Doodle','4:5','Static',8],['Static offer','4:5','Static',3],['Tier list','1:1','Static',20]];
function rsAssetCount(s){return Number.isInteger(s.assetsPerCell)&&s.assetsPerCell>=4&&s.assetsPerCell<=12&&s.assetsPerCell%2===0?s.assetsPerCell:6}
function rsRecipe(c){var formats=c.lane==='skin'?RS_SKIN_FORMATS:RS_KIT_FORMATS;return Array.from({length:rsAssetCount(rsState())},function(_,i){var f=formats[i%formats.length].slice();if(i>=formats.length)f[0]+=' · execution 2';return f})}
function rsRosterIssues(c){var items=rsCellItems(c),issues=[];if(items.length<4||items.length>12)issues.push('Keep 4–12 active assets in this cell');if(items.some(function(x){return x.concept!==c.concept}))issues.push('Assets must use this cell’s single variant');return issues}
function rsBatch(cellId){var c=rsCell(cellId);if(!c||c.kind==='Mixed')return 0;var n=0,at=new Date().toISOString();var remaining=Math.max(0,rsAssetCount(rsState())-rsCellItems(c).length);rsRecipe(c).forEach(function(f,i){if(n>=remaining)return;var slot=cellId+'-slot-'+(i+1);if(plItems().some(function(x){return x.restartSlot===slot}))return;var p=c.lane==='skin'?'P02':'P01',ratio=f[1].split(':').map(Number);plItems().push({id:wsId('pipeline'),restartSlot:slot,restartCell:cellId,name:p+'_C'+String(c.index).padStart(2,'0')+'_A01_H01_CR01_F'+String(f[3]).padStart(2,'0')+'_V'+String(Math.floor(i/6)+1).padStart(2,'0')+' · '+f[0],product:rsProduct(c.lane),campaign:rsCampaign(c),concept:c.concept,copyStructure:c.lane==='skin'?'Skincare · direct':'Kit · indirect',copyCta:c.lane==='skin'?'Shop now':'See what is inside',format:f[2],creativeStyle:f[0],requiredRatio:f[1],width:1080,height:Math.round(1080*ratio[1]/ratio[0]),owner:rsState().owner,stage:'Brief',winnerStage:'Unproven',outcome:'Pending',variable:'Concept between ad sets; matched format menu inside each',control:'Same broad US 18+ audience, exclusions, offer, destination, attribution and bid strategy across cells',hypothesis:'Draft: If '+c.concept+' addresses the selected motivation, backend CPA may improve. Specify the reason and comparison before launch.',guardrail:'Stop for account risk, tracking failure or declared maximum loss; do not infer a concept winner from uneven asset delivery.',targetCpa:c.lane==='skin'?rsState().skinCpa:rsState().kitCpa,createdAt:at,stageEnteredAt:at,history:[{stage:'Brief',at:at}]});n++});return n}
function rsCellItems(c){return plItems().filter(function(x){return x.restartCell===c.id&&x.stage!=='Archived'})}
function rsReadIssues(r,today){var issues=[],c=rsCell(r.cell),s=rsState();today=today||wsToday();if(!c)return ['Cell not in current plan'];if(!plValidDate(r.start)||!plValidDate(r.end)||r.end<r.start)issues.push('Valid comparison window required');if(!plValidDate(r.readAfter)||r.readAfter<r.end||r.readAfter>today)issues.push('Wait for conversion lag');if(!(r.minimumSpend>0&&r.minimumOrders>0&&r.spend>=r.minimumSpend&&r.orders>=r.minimumOrders))issues.push('Predeclared evidence not met');if(!(r.orders>0&&r.spend/r.orders<=(c.lane==='skin'?s.skinCpa:s.kitCpa)))issues.push('Backend CPA above target or unmeasurable');if(!r.comparable||!r.clean||!r.finding||!r.limits||!wsSafeLink(r.evidence))issues.push('Comparable conditions, health, finding, limits and evidence required');if(r.decision==='Confirmed concept'&&(c.kind==='Mixed'||!r.confirmed))issues.push('Concept confirmation needs a concept cell and a separate confirmation read');return issues}
function rsCellsView(){var s=rsState(),cells=rsCells();return '<h3>4 ABO ad sets · 1 variant each · 4–12 assets per cell</h3><p>Broad US 18+ acquisition · Sales / Purchase · highest volume · ABO · matched audience, exclusions, offer, destination and attribution. The PDF specifies Advantage+ placements and 7-day click / 1-day view; verify availability in the actual account.</p><div class="pl-notice">ABO allocates budget; it does not randomize people. These are directional cell comparisons. Keep one variant inside each ad set. Match the other conditions across all four cells; formats are executions of that same variant. Repeat the result or use an appropriate controlled experiment before calling it confirmed.</div><form id="rs-concepts" class="panel"><h3>Define the four variants for each product</h3><div class="pl-grid">'+['skin','kit'].map(function(lane){return '<fieldset><legend>'+plE(rsProduct(lane))+'</legend>'+(lane==='skin'?s.skinConcepts:(s.kitConcepts||rsDefaults().kitConcepts)).map(function(v,i){return rsInput(lane+'Concept'+i,'Ad set '+(i+1)+' · variant',v,'text','required')}).join('')+'</fieldset>'}).join('')+'<label>Assets per cell (even, 4–12)<select name="assetsPerCell">'+[4,6,8,10,12].map(function(n){return '<option value="'+n+'" '+(rsAssetCount(s)===n?'selected':'')+'>'+n+' assets</option>'}).join('')+'</select></label></div><p>'+rsAssetCount(s)*4+' planned assets per product campaign · '+rsAssetCount(s)*8+' across both products. Existing briefs retain their names and history; reconcile any variant mismatch before testing.</p><p id="rs-concept-errors" role="alert"></p><button class="btn">Save test structure</button></form><div class="rs-cell-grid">'+cells.map(function(c){var e=rsEconomics(s,c.lane),items=rsCellItems(c),ratios=new Set(items.map(function(x){return x.requiredRatio}));return '<article class="panel rs-cell"><span class="rs-kicker">'+(c.kind==='Mixed'?'PERFORMANCE ONLY':plE(c.lane==='skin'?'SKINCARE':'KIT')+' · CONCEPT CELL')+'</span><h3>'+plE(c.concept)+'</h3><p class="rs-code">'+rsCampaign(c)+'<br>AS0'+c.index+'_BROAD_'+(c.kind==='Mixed'?'MIXED':'CONCEPT')+'</p><p><b>'+wsMoney(e.perCell)+'/day</b> · '+e.weeklyOrders.toFixed(1)+' expected orders/week</p><p>'+items.length+' active briefs / '+rsAssetCount(s)+' planned · '+['9:16','4:5','1:1'].filter(function(r){return ratios.has(r)}).length+'/3 ratios covered</p>'+(c.kind==='Mixed'?'<p>Reuse selected existing winners by their asset ID. Six placements are not six new productions. Read this pool separately.</p>':'<p>'+rsRecipe(c).map(function(f){return plE(f[0])+' '+f[1]}).join(' · ')+'</p><button class="btn" data-rs="batch" data-cell="'+c.id+'">Fill to '+rsAssetCount(s)+' draft briefs</button>')+'<p class="pl-bad">'+plE(rsRosterIssues(c).join('; '))+'</p><button class="btn" data-rs="read" data-cell="'+c.id+'">Record cell read</button></article>'}).join('')+'</div><p id="rs-feedback" role="status"></p>'+rsReadForm()+
 '<h3>Cell decisions</h3>'+plTable(['Cell / window','CPA','Declared decision','Evidence review','Next step'],s.reads.map(function(r){var c=rsCell(r.cell),issues=rsReadIssues(r);return [plE(c?c.concept:r.cell)+'<br>'+plE(r.start+' → '+r.end),r.orders>0?wsMoney(r.spend/r.orders):'No valid orders',plE(r.decision),plE(issues.join('; ')||'Recorded criteria clear; observational evidence'),plE(r.next)]}))+
 '<details class="rs-details"><summary>Copy structure and production rules</summary><div class="rs-lanes"><div><h4>Kit · indirect</h4><p>Situation hook (6–12 words) → calm reframe → name the non-Rx product → one verified factual proof → Learn more / See what is inside.</p><p>Use actual contents, authorship, shipping or verified rating/count. No AC-01 inheritance; the PDF conflicts on its use. Do not imply access to prescription contents.</p></div><div><h4>Skincare · direct</h4><p>Cosmetic hook → concrete texture, ingredient or routine detail → verified proof → accurate price or subscription terms → Shop now.</p><p>Skincare still needs copy and destination review. Cosmetic positioning does not grant blanket eligibility or remove substantiation requirements.</p></div></div><p>Restart exclusions: transformation, symptom lists, outcome testimonials, side-effect claims, warnings, prevention promises, quantified health outcomes and other claim-bearing formats. A safe-looking container cannot make an unsafe claim acceptable. Quiz pages still require review and appropriate handling of sensitive data.</p><p>Each ad set carries one variant with four to twelve assets. Assets 7–12 are additional execution drafts of the same six format containers, with distinct version IDs; complete each brief before launch. The selected asset count uses a matched format menu with 9:16, 4:5 and 1:1 coverage. The PDF gives different kit menus; this implementation matches them across kit cells to reduce format confounding. Archive or revise drafts deliberately; batch creation never overwrites existing work.</p></details>'+
 '<h3>After a confirmed read</h3>'+plTable(['Stage','Structure','Decision'],[['Month 2','70% acquisition scale CBO / 15% angle-test ABO / 15% separate retargeting ABO','Graduate confirmed concepts. Angle tests keep the concept fixed: four ABO ad sets, one angle variant each, four to twelve assets per cell. Review funding and read duration if the test allocation is thin.'],['Month 3','Same two products; fortnightly replacement batch','Prove sustained backend efficiency. Test format later; log material changes. Frequency 4/7 days is a review flag, not an assumed configurable purchase-campaign cap.'],['Month 4+','Expansion only after all day-90 conditions','New products, catalog scope and creator attribution each need their own readiness review. Written product/domain authorization is required where applicable.']])}
var rsReading='';
function rsReadForm(){var s=rsState(),r=s.reads.find(function(x){return x.cell===rsReading})||{cell:rsReading||rsCells()[0].id,decision:'Inconclusive'};return '<details class="rs-details" '+(rsReading?'open':'')+'><summary>Record a mature, comparable cell read</summary><form id="rs-read"><div class="pl-grid"><label>Cell<select name="cell">'+rsCells().map(function(c){return '<option value="'+c.id+'" '+(r.cell===c.id?'selected':'')+'>'+plE(c.lane+' · '+c.concept)+'</option>'}).join('')+'</select></label>'+[['start','Window start','date'],['end','Window end','date'],['readAfter','Read after conversion lag','date'],['spend','Cell spend, USD','number'],['orders','Backend valid orders','number'],['minimumSpend','Predeclared minimum spend','number'],['minimumOrders','Predeclared minimum valid orders','number'],['evidence','Read / confirmation evidence URL','url']].map(function(f){return rsInput(f[0],f[1],r[f[0]]==null?'':r[f[0]],f[2],f[2]==='number'?'min="0" step="any" required':'required')}).join('')+'<label>Decision<select name="decision">'+rsOptions(['Inconclusive','Stop for risk','Loss','Promising','Confirmed concept','Asset candidate'],r.decision)+'</select></label>'+rsCheck('comparable','Audience, offer, destination, window and measurement comparable',r.comparable)+rsCheck('clean','No unresolved disapproval or signal issue in this read',r.clean)+rsCheck('confirmed','Separate confirmation read documented in evidence',r.confirmed)+['finding','limits','next'].map(function(k){return '<label>'+({finding:'Finding',limits:'Confounds and limits',next:'Next action'})[k]+'<textarea name="'+k+'" required>'+plE(r[k])+'</textarea></label>'}).join('')+'</div><p>One current read per cell; saving replaces it and records the action in the audit log. Minimum criteria must be chosen before reading results. No automatic graduation or media changes.</p><p id="rs-read-errors" role="alert"></p><button class="btn p">Save cell read</button></form></details>'}
function rsDayIssues(d,today){var issues=[];if(!plValidDate(d.date)||d.date>(today||wsToday()))issues.push('Use a valid date no later than today');['skinSpend','skinOrders','skinMeta','kitSpend','kitOrders','kitMeta','disapprovals'].forEach(function(k){if(!plFinite(d[k])||d[k]<0||(/Orders|Meta|disapprovals/.test(k)&&!Number.isInteger(d[k])))issues.push(k+' requires a nonnegative '+(/Spend/.test(k)?'number':'whole number'))});if(!String(d.evidence||'').trim())issues.push('Evidence reference is required');return issues}
function rsGate(s,today){s=s||rsState();today=today||wsToday();var validStart=plValidDate(s.start),end=validStart?wsShift(s.start,89):'',elapsed=validStart?Math.max(0,plDayDiff(s.start,today)+1):0,rows=validStart?s.days.filter(function(d){return d.date>=s.start&&d.date<=end&&d.date<=today&&!rsDayIssues(d,today).length}):[],byDate=new Map(rows.map(function(d){return [d.date,d]})),full=elapsed>=90&&byDate.size===90,days=Array.from(byDate.values()),last=validStart?Array.from({length:14},function(_,i){return byDate.get(wsShift(end,i-13))}):[],cpa=last.length===14&&['skin','kit'].some(function(l){return last.every(function(d){return d&&d[l+'Orders']>0&&d[l+'Spend']/d[l+'Orders']<=(l==='skin'?s.skinCpa:s.kitCpa)})}),recon=last.length===14&&last.every(function(d){return d&&d.matched})&&['skin','kit'].every(function(l){var b=last.reduce(function(n,d){return n+(d?d[l+'Orders']:0)},0),m=last.reduce(function(n,d){return n+(d?d[l+'Meta']:0)},0);return b>0&&Math.abs(m-b)/b<=.15}),wins={skin:0,kit:0},seen={skin:new Set(),kit:new Set()};plItems().filter(plValidated).forEach(function(x){var c=rsCell(x.restartCell);if(c&&x.product===rsProduct(c.lane)){var asset=x.assetId||x.assetUrl;if(asset&&!seen[c.lane].has(asset)){seen[c.lane].add(asset);wins[c.lane]++}}});var health=full&&days.every(function(d){return d.health&&d.disapprovals===0}),creative=wins.skin>=2&&wins.kit>=2;return {end:end,elapsed:elapsed,logged:byDate.size,full:full,cpa:cpa,recon:recon,wins:wins,creative:creative,health:health,pass:full&&cpa&&recon&&creative&&health&&rsLaunchIssues(s).length===0}}
function rsGateView(){var s=rsState(),g=rsGate(s);return '<div class="rs-status"><div><span class="rs-kicker">Expansion decision</span><h3>'+(g.pass?'Recorded gates clear for review':'Deepen the two products until all gates clear')+'</h3><p>Day 90: '+plE(g.end||'Set restart date')+' · '+g.logged+'/90 daily records.</p></div><div class="rs-state '+(g.pass?'rs-clear':'rs-hold')+'">'+(g.pass?'REVIEW EXPANSION':'HOLD EXPANSION')+'</div></div>'+plTable(['Plan condition','Recorded status','Definition used'],[
 ['14 consecutive days at target CPA',g.cpa?'Clears':'Missing / not met','At least one product; each of the final 14 days has valid orders and backend CPA at or below its target.'],['Meta/backend difference within 15%',g.recon?'Clears':'Missing / not met','Each product, final 14 days combined; absolute order difference / backend orders. Matching attribution and order scope explicitly recorded.'],['Two validated creatives per product',g.creative?'Clears':'Missing / not met','Linked pipeline items clearing current validation: product two '+g.wins.skin+', kit '+g.wins.kit+'.'],['Zero disapprovals in 90 days',g.health?'Clears':'Missing / not met','90 unique daily records, health checked, no disapprovals. Missing days cannot count as clean.']])+ '<p class="pl-notice">A clear gate is an internal expansion review, not permission to advertise restricted products. The PDF leaves the reconciliation window unspecified; this tool uses the final 14 days and shows that choice. Zero-order days do not prove CPA. Historical plan failures remain visible.</p>'+rsDayForm()+
 '<h3>Daily restart ledger</h3>'+plTable(['Date','Product two spend / orders','Kit spend / orders','Health','Reconciled scope','Action'],s.days.slice().sort(function(a,b){return b.date.localeCompare(a.date)}).map(function(d){return [plE(d.date),wsMoney(d.skinSpend)+' / '+d.skinOrders,wsMoney(d.kitSpend)+' / '+d.kitOrders,d.health?d.disapprovals+' disapprovals':'Not checked',d.matched?'Matched':'Unconfirmed','<button class="btn" data-rs="day" data-date="'+plE(d.date)+'">Edit</button>']}))}
var rsDayEditing='';
function rsDayForm(){var d=rsState().days.find(function(x){return x.date===rsDayEditing})||{date:wsToday()};return '<details class="rs-details" '+(rsDayEditing?'open':'')+'><summary>Add or correct a daily record</summary><form id="rs-day"><div class="pl-grid">'+rsInput('date','Date',d.date,'date','required')+[['skinSpend','Product two spend'],['skinOrders','Product two valid backend orders'],['skinMeta','Product two matched Meta orders'],['kitSpend','Kit spend'],['kitOrders','Kit valid backend orders'],['kitMeta','Kit matched Meta orders'],['disapprovals','New disapprovals across both products']].map(function(f){return rsInput(f[0],f[1],d[f[0]]==null?'':d[f[0]],'number','min="0" step="'+(/Spend/.test(f[0])?'any':'1')+'" required')}).join('')+rsCheck('health','Account health checked today',d.health)+rsCheck('matched','Meta/backend attribution, timezone and order scope matched',d.matched)+rsInput('evidence','Evidence reference / health and measurement notes',d.evidence||'','text','required')+'</div><p>One record per date. This manual ledger supports the restart gate and does not duplicate rows into performance reports.</p><p id="rs-day-errors" role="alert"></p><button class="btn p">Save daily record</button></form></details>'}
function rsSavePlan(form){var d=new FormData(form),s=rsState(),next=Object.assign({},s),errors=[];['start','reason','reasonEvidence','owner','backup','decision','skinName','kitName','checkEvidence','catalogEvidence'].forEach(function(k){next[k]=String(d.get(k)||'').trim()});['remediated','alternativeReviewed','accepted','catalogTier','catalogSet','catalogReview'].forEach(function(k){next[k]=d.has(k)});next.skinCpa=Number(d.get('skinCpa'));next.kitCpa=Number(d.get('kitCpa'));next.week=Number(d.get('week'));next.ramp=[0,1,2,3].map(function(i){return Number(d.get('ramp'+i))});next.checks={};RS_CHECKS.forEach(function(c){next.checks[c[0]]=d.has('check_'+c[0])});if(next.start&&!plValidDate(next.start))errors.push('Invalid start date');if(!(next.skinCpa>0&&next.kitCpa>0)||![1,2,3,4].includes(next.week)||next.ramp.some(function(v){return !Number.isFinite(v)||v<0}))errors.push('Use positive CPA targets and nonnegative budgets');if(!next.skinName||!next.kitName||next.skinName===next.kitName)errors.push('Name two distinct reviewed products');if(s.days.length&&plValidDate(s.start)&&next.start!==s.start)errors.push('Start date is locked once daily records exist');if(plItems().some(function(x){return x.restartCell})&&(next.skinName!==s.skinName||next.kitName!==s.kitName))errors.push('Product names are locked after linked briefs exist; preserve their identity');if(errors.length){$('rs-plan-errors').textContent=errors.join('. ');return}plState().restart=next;plChanged('Restart decisions saved',{name:'Account restart',id:''})}
function rsSaveRead(form){var d=new FormData(form),r={};['cell','start','end','readAfter','evidence','decision','finding','limits','next'].forEach(function(k){r[k]=String(d.get(k)||'').trim()});['spend','orders','minimumSpend','minimumOrders'].forEach(function(k){r[k]=plN(d.get(k))});['comparable','clean','confirmed'].forEach(function(k){r[k]=d.has(k)});var errors=[];if(!rsCell(r.cell)||!plValidDate(r.start)||!plValidDate(r.end)||r.end<r.start||!plValidDate(r.readAfter)||r.readAfter<r.end)errors.push('Valid cell, dates and read window required');if(['spend','orders','minimumSpend','minimumOrders'].some(function(k){return !plFinite(r[k])||r[k]<0})||!Number.isInteger(r.orders)||!Number.isInteger(r.minimumOrders))errors.push('Use valid nonnegative metrics and whole order counts');if(['Confirmed concept','Promising','Asset candidate'].includes(r.decision))errors=errors.concat(rsReadIssues(r));if(errors.length){$('rs-read-errors').textContent=errors.join('. ');return}var old=rsState().reads.find(function(x){return x.cell===r.cell});r.previous=old?{decision:old.decision,start:old.start,end:old.end,evidence:old.evidence}:null;r.updatedAt=new Date().toISOString();if(old)Object.assign(old,r);else rsState().reads.push(r);rsReading='';plChanged('Restart cell read saved',{name:r.cell+' · '+r.decision,id:r.cell})}
function rsSaveStructure(form){var data=new FormData(form),s=rsState(),values={},count=Number(data.get('assetsPerCell'));['skin','kit'].forEach(function(lane){values[lane]=[0,1,2,3].map(function(i){return String(data.get(lane+'Concept'+i)||'').trim()})});if(!(Number.isInteger(count)&&count>=4&&count<=12&&count%2===0)||['skin','kit'].some(function(lane){return values[lane].some(function(v){return !v})||new Set(values[lane].map(function(v){return v.toLowerCase()})).size!==4})){$('rs-concept-errors').textContent='Choose an even asset count: 4, 6, 8, 10 or 12, plus four distinct variants per product.';return}s.skinConcepts=values.skin;s.kitConcepts=values.kit;s.assetsPerCell=count;s.version=2;plChanged('Four-cell ABO structure saved',{name:'Both product campaigns',id:''})}
function rsBind(){var root=$('pipeline-app');if(!root)return;root.addEventListener('submit',function(e){if(!/^rs-/.test(e.target.id))return;e.preventDefault();if(e.target.id==='rs-plan')rsSavePlan(e.target);if(e.target.id==='rs-concepts'){rsSaveStructure(e.target)}if(e.target.id==='rs-read')rsSaveRead(e.target);if(e.target.id==='rs-day'){var data=new FormData(e.target),row={date:String(data.get('date')||''),evidence:String(data.get('evidence')||'').trim(),health:data.has('health'),matched:data.has('matched')};['skinSpend','skinOrders','skinMeta','kitSpend','kitOrders','kitMeta','disapprovals'].forEach(function(k){row[k]=plN(data.get(k))});var errors=rsDayIssues(row);if(rsDayEditing&&row.date!==rsDayEditing)errors.push('Date is fixed when correcting a record');if(errors.length){$('rs-day-errors').textContent=errors.join('. ');return}var old=rsState().days.find(function(x){return x.date===row.date});if(old)Object.assign(old,row);else rsState().days.push(row);rsDayEditing='';plChanged('Restart daily evidence saved',{name:row.date,id:row.date})}});root.addEventListener('click',function(e){var b=e.target.closest('[data-rs]');if(!b)return;if(b.dataset.rs==='batch'){var n=rsBatch(b.dataset.cell);plChanged('Created '+n+' restart briefs',{name:b.dataset.cell,id:b.dataset.cell});$('rs-feedback').textContent=n+' new drafts created. Existing briefs preserved. Open Production board to complete and approve them.'}if(b.dataset.rs==='read'){rsReading=b.dataset.cell;renderPipeline()}if(b.dataset.rs==='day'){rsDayEditing=b.dataset.date;renderPipeline()}})}
rsBind();
